#!/bin/bash

# Define the list of topics
topics=(
  /aruco_detect/markers_left
  /aruco_detect/markers_right
  /behavior_server/transition_event
  /bond
  /bt_navigator/transition_event
  /camera_left/color/camera_info
  /camera_left/color/image_raw
  /camera_right/color/camera_info
  /camera_right/color/image_raw
  /clock
  /cloud_ground
  /cloud_map
  /cloud_obstacles
  /cmd_vel
  /cmd_vel_final
  /cmd_vel_nav
  /cmd_vel_teleop
  /controller_server/transition_event
  /cost_cloud
  /diagnostics
  /docking
  /elevation_map
  /evaluation
  /global_costmap/costmap
  /global_costmap/costmap_raw
  /global_costmap/costmap_updates
  /global_costmap/footprint
  /global_costmap/global_costmap/transition_event
  /global_costmap/published_footprint
  /global_path
  /global_path_nodes
  /global_pose
  /goal
  /goal_node
  /goal_out
  /goal_pose
  /goal_reached
  /gps/fix
  /grid_prob_map
  /imu
  /info
  /initialpose
  /joint_states
  /joy
  /joy/set_feedback
  /labels
  /landmark_detection
  /landmark_detections
  /landmarks
  /lidar_packets
  /lidar_packets_loss
  /local_costmap/clearing_endpoints
  /local_costmap/costmap
  /local_costmap/costmap_raw
  /local_costmap/costmap_updates
  /local_costmap/footprint
  /local_costmap/local_costmap/transition_event
  /local_costmap/published_footprint
  /local_costmap/voxel_grid
  /local_grid_empty
  /local_grid_ground
  /local_grid_obstacle
  /local_path
  /local_path_nodes
  /local_plan
  /localization_pose
  /map
  /mapData
  /mapGraph
  /mapOdomCache
  /mapPath
  /map_server/transition_event
  /marker
  /octomap_binary
  /octomap_empty_space
  /octomap_full
  /octomap_global_frontier_space
  /octomap_grid
  /octomap_ground
  /octomap_obstacles
  /octomap_occupied_space
  /odom
  /parameter_events
  /plan
  /plan_smoothed
  /planner_server/transition_event
  /preempt_teleop
  /real_vel
  /received_global_plan
  /robot_description
  /rosout
  /rtabmap_localizer/republish_node_data
  /scan_filtered
  /scan_laserscan
  /scan_pointcloud
  /smoother_server/transition_event
  /speed_limit
  /tf
  /tf_static
  /transformed_global_plan
  /user_data_async
  /velocity_smoother/transition_event
  /waypoint_follower/transition_event
)

# Start recording the bag
ros2 bag record "${topics[@]}"
